/* Atlas shared data — the 180-site starter library, the tag colour system,
   and the 3 Explore groups (planning doc §7). Used by explore.js. */
(function (root) {
  root.ATLAS_GROUPS = [
    { bg: "#3A3A3D", fg: "#C7C7CC", tags: ["Tool", "Library"] },
    { bg: "#4A382E", fg: "#D8B79A", tags: ["Mockup", "3D"] },
    { bg: "#5A3B1E", fg: "#F3A85B", tags: ["Icon", "Component"] },
    { bg: "#524A16", fg: "#E8D468", tags: ["Color", "Font"] },
    { bg: "#24402A", fg: "#86D89A", tags: ["Web", "App", "Ecommerce"] },
    { bg: "#1F4547", fg: "#7FD4D9", tags: ["UX", "Interaction", "Motion"] },
    { bg: "#1F3A5F", fg: "#8AB4F8", tags: ["Inspiration", "Portfolio", "Image"] },
    { bg: "#3A2E54", fg: "#C3A6F0", tags: ["AI Design", "Design System"] },
    { bg: "#55293F", fg: "#F0A8C7", tags: ["Branding", "Graphic Design"] },
    { bg: "#55231F", fg: "#F5A399", tags: ["Email"] }
  ];

  root.ATLAS_GROUP_DEFS = [
    { key: "Reference", title: "Reference",
      blurb: "Sites you look at — real products, cases and galleries to study before you start.",
      tags: ["Web", "App", "UX", "Branding", "Graphic Design", "Portfolio", "Inspiration", "Ecommerce", "Email"] },
    { key: "Visual Asset Explore", title: "Visual Asset Explore",
      blurb: "Material you download and drop straight into the work — icons, type, imagery, colour, mockups.",
      tags: ["Icon", "Font", "Image", "Color", "Mockup", "3D"] },
    { key: "Experimental Design Opensource", title: "Experimental Design Opensource",
      blurb: "Code- and tech-based resources — components, motion, design systems and tools.",
      tags: ["Component", "Design System", "Motion", "Interaction", "Tool", "AI Design", "Library"] }
  ];
  root.ATLAS_GROUP_PRIORITY = ["Visual Asset Explore", "Reference", "Experimental Design Opensource"];

  root.ATLAS_VIEWS = [
    { id: "all", label: "All", group: null },
    { id: "starred", label: "Starred", starred: true },
    { id: "reference", label: "Reference", group: "Reference" },
    { id: "asset", label: "Design Asset", group: "Visual Asset Explore" },
    { id: "tools", label: "Tools", group: "Experimental Design Opensource" }
  ];

  root.ATLAS_SITES = [
    { n: "Curated", u: "https://www.curated.design", d: "Hand-picked, high-quality web design references.", t: ["Web", "Inspiration"] },
    { n: "Siteinspire", u: "https://www.siteinspire.com", d: "Website design archive organised by style and type.", t: ["Web", "Inspiration"] },
    { n: "Godly", u: "https://godly.website", d: "Interaction-led web design curation.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "Awwwards", u: "https://www.awwwards.com", d: "Global web design awards and reference gallery.", t: ["Web", "Inspiration"] },
    { n: "Minimal Gallery", u: "https://minimal.gallery", d: "A collection of minimal website design.", t: ["Web", "Inspiration"] },
    { n: "Maxi Best Of One", u: "https://maxibestof.one", d: "Curation of web, branding and digital design.", t: ["Web", "Branding", "Inspiration"] },
    { n: "Steep", u: "https://www.steep.design", d: "References for social and story design.", t: ["Graphic Design", "Inspiration"] },
    { n: "Portfolio Project", u: "https://portfolioproject.io", d: "Designer and developer portfolios in one place.", t: ["Portfolio", "Inspiration"] },
    { n: "Dark Mode Design", u: "https://www.darkmodedesign.com", d: "An archive of dark mode UI design.", t: ["Web", "App", "Inspiration"] },
    { n: "Spotted in Prod", u: "https://www.spottedinprod.com", d: "Real iOS app UI and interaction, captured on video.", t: ["App", "Interaction", "Inspiration"] },
    { n: "Footer Design", u: "https://footer.design", d: "A gallery of website footer designs.", t: ["Web", "Component", "Inspiration"] },
    { n: "Mobbin", u: "https://mobbin.com", d: "Searchable archive of real app UI and user flows.", t: ["App", "Web", "UX", "Inspiration"] },
    { n: "Refero", u: "https://refero.design", d: "Search real product UX patterns by screen.", t: ["UX", "App", "Inspiration"] },
    { n: "Userspoon", u: "https://diby.io/upa", d: "UX patterns and user journeys, local and global.", t: ["UX", "Inspiration"] },
    { n: "Notefolio", u: "https://notefolio.net", d: "Korean designer portfolio platform.", t: ["Portfolio", "Inspiration"] },
    { n: "DBCUT", u: "https://www.dbcut.com", d: "Reference archive of Korean websites.", t: ["Web", "Inspiration"] },
    { n: "Landing Love", u: "https://www.landing.love", d: "Curation of high-quality landing pages.", t: ["Web", "Inspiration"] },
    { n: "Lapa Ninja", u: "https://www.lapa.ninja", d: "Landing page reference gallery.", t: ["Web", "Inspiration"] },
    { n: "Land-book", u: "https://land-book.com", d: "A large archive of landing page design.", t: ["Web", "Inspiration"] },
    { n: "SaaSpo", u: "https://www.saaspo.com", d: "SaaS UI design examples, page by page.", t: ["Web", "App", "Inspiration"] },
    { n: "Httpster", u: "https://httpster.net", d: "Experimental and brutalist websites.", t: ["Web", "Inspiration"] },
    { n: "MUUUUU.ORG", u: "https://muuuuu.org", d: "Japanese web design archive.", t: ["Web", "Inspiration"] },
    { n: "One Page Love", u: "https://onepagelove.com", d: "References for one-page sites.", t: ["Web", "Inspiration"] },
    { n: "Romotion", u: "https://romotion.io", d: "SaaS and startup web design with motion.", t: ["Web", "Motion", "Inspiration"] },
    { n: "Lucide", u: "https://lucide.dev", d: "Open-source SVG icon set.", t: ["Icon", "Library"] },
    { n: "Heroicons", u: "https://heroicons.com", d: "The official Tailwind icon set.", t: ["Icon", "Library"] },
    { n: "Flaticon", u: "https://www.flaticon.com", d: "Large icon and sticker library.", t: ["Icon", "Library"] },
    { n: "Circum Icons", u: "https://circumicons.com", d: "A minimal, single-weight icon set.", t: ["Icon", "Library"] },
    { n: "Hugeicons", u: "https://hugeicons.com", d: "Premium icon library with many styles.", t: ["Icon", "Library"] },
    { n: "Component Gallery", u: "https://component.gallery", d: "How real design systems build each component.", t: ["Component", "Design System"] },
    { n: "Untitled UI", u: "https://www.untitledui.com", d: "Figma UI kit and design system.", t: ["Design System", "Component", "Library"] },
    { n: "Navbar Gallery", u: "https://www.navbar.gallery", d: "A collection of navigation UI.", t: ["Component", "Inspiration"] },
    { n: "CTA Gallery", u: "https://www.cta.gallery", d: "Call-to-action buttons and sections.", t: ["Component", "Inspiration"] },
    { n: "Unsplash", u: "https://unsplash.com", d: "Free high-resolution photography.", t: ["Image", "Library"] },
    { n: "Pexels", u: "https://www.pexels.com", d: "Free stock photos and video.", t: ["Image", "Library"] },
    { n: "Google Fonts", u: "https://fonts.google.com", d: "Free, open-source web font library.", t: ["Font", "Library"] },
    { n: "Coolors", u: "https://coolors.co", d: "Fast colour palette generator.", t: ["Color", "Tool"] },
    { n: "Color Hunt", u: "https://colorhunt.co", d: "A feed of trendy colour palettes.", t: ["Color", "Inspiration"] },
    { n: "ColorHub", u: "https://colorhub.app", d: "Colour discovery and recommendation.", t: ["Color", "Tool"] },
    { n: "Kigen Design", u: "https://kigen.design/color", d: "Generate a systematic colour scale.", t: ["Color", "Tool"] },
    { n: "Grabient", u: "https://www.grabient.com", d: "CSS gradient generator.", t: ["Color", "Tool"] },
    { n: "Gradients Colorion", u: "https://gradients.colorion.co", d: "A library of ready-made gradients.", t: ["Color", "Library"] },
    { n: "Tooooools", u: "https://www.tooooools.app", d: "Browser tools for graphic effects.", t: ["Tool", "Graphic Design"] },
    { n: "Remove.bg", u: "https://www.remove.bg", d: "AI background removal for images.", t: ["Tool", "AI Design", "Image"] },
    { n: "TinyPNG", u: "https://tinypng.com", d: "Smart lossy compression for PNG and JPEG.", t: ["Tool", "Image"] },
    { n: "Law of UX", u: "https://lawsofux.com", d: "A collated set of UX heuristics and laws.", t: ["UX", "Library"] },
    { n: "Nielsen Norman Group", u: "https://www.nngroup.com", d: "UX research articles and guidelines.", t: ["UX", "Library"] },
    { n: "UX Collective", u: "https://uxdesign.cc", d: "A steady stream of UX writing.", t: ["UX", "Library"] },
    { n: "It's Nice That", u: "https://www.itsnicethat.com", d: "Design and creative-industry news.", t: ["Graphic Design", "Inspiration"] },
    { n: "AURG Design", u: "https://www.aurg.kr", d: "Branding and package design studio work.", t: ["Branding", "Graphic Design"] },
    { n: "Brandpad", u: "https://brandpad.io", d: "A platform for building brand guidelines.", t: ["Branding", "Tool"] },
    { n: "Visuelle", u: "https://visuelle.co.uk", d: "A daily feed of branding references.", t: ["Branding", "Inspiration"] },
    { n: "Rebrand Gallery", u: "https://www.rebrand.gallery", d: "Before-and-after global rebrands.", t: ["Branding", "Inspiration"] },
    { n: "Design Everywhere", u: "https://designeverywhere.co", d: "An archive of graphic design in the wild.", t: ["Graphic Design", "Inspiration"] },
    { n: "Cosmos", u: "https://www.cosmos.so", d: "Save and explore visual references.", t: ["Inspiration", "Image"] },
    { n: "Savee", u: "https://savee.com", d: "Collect visual references into boards.", t: ["Inspiration", "Image"] },
    { n: "Behance", u: "https://www.behance.net", d: "Global creative portfolio network.", t: ["Portfolio", "Inspiration"] },
    { n: "Dribbble", u: "https://dribbble.com", d: "UI and branding shots from designers.", t: ["Inspiration", "Portfolio", "Branding"] },
    { n: "Design Spells", u: "https://www.designspells.com", d: "Small delightful details, catalogued.", t: ["Interaction", "Inspiration"] },
    { n: "Recent Design", u: "https://recent.design", d: "A running list of current design trends.", t: ["Inspiration"] },
    { n: "Collect UI", u: "https://collectui.com", d: "Daily UI inspiration, sorted by pattern.", t: ["Component", "Inspiration"] },
    { n: "UX Bites", u: "https://builtformars.com/ux-bites", d: "Short teardowns of real product UX.", t: ["UX", "Inspiration"] },
    { n: "Design Vault", u: "https://designvault.io", d: "A searchable store of UI patterns.", t: ["Component", "UX", "Inspiration"] },
    { n: "Details Matter", u: "https://detailsmatter.framer.website", d: "A study of micro-interactions.", t: ["Interaction", "Motion", "Inspiration"] },
    { n: "Viewport UI", u: "https://viewport-ui.design", d: "Curated UI across web and mobile.", t: ["Web", "App", "Inspiration"] },
    { n: "Unsection", u: "https://www.unsection.com", d: "Web page sections, isolated as references.", t: ["Web", "Component", "Inspiration"] },
    { n: "Dark", u: "https://www.dark.design", d: "References for dark UI.", t: ["Web", "App", "Inspiration"] },
    { n: "Browsing Mode", u: "https://browsingmode.com", d: "Experimental web design, collected.", t: ["Web", "Inspiration"] },
    { n: "Dead Simple Sites", u: "https://deadsimplesites.com", d: "Deliberately minimal websites.", t: ["Web", "Inspiration"] },
    { n: "The Whimsical Web", u: "https://whimsical.club", d: "Personal sites with character.", t: ["Web", "Inspiration"] },
    { n: "Hoverstat.es", u: "https://hoverstat.es", d: "Experimental interaction on real sites.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "Three.js Paris", u: "https://threejs.paris", d: "A showcase of Three.js-based 3D web.", t: ["3D", "Web", "Inspiration"] },
    { n: "Buttermax", u: "https://buttermax.net", d: "Motion-forward web experiences.", t: ["Motion", "Web", "Inspiration"] },
    { n: "Supahero", u: "https://www.supahero.io", d: "A gallery of hero sections.", t: ["Web", "Component", "Inspiration"] },
    { n: "OGimage.gallery", u: "https://ogimage.gallery", d: "Open Graph share-image examples.", t: ["Graphic Design", "Inspiration"] },
    { n: "404s", u: "https://www.404s.design", d: "A collection of 404 page designs.", t: ["Web", "Inspiration"] },
    { n: "Pricing Pages", u: "https://pricingpages.design", d: "Real pricing page layouts.", t: ["Web", "Component", "Inspiration"] },
    { n: "Websitevice", u: "https://websitevice.com", d: "Practical, working website references.", t: ["Web", "Inspiration"] },
    { n: "The FWA", u: "https://thefwa.com", d: "Awards and showcase for interactive sites.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "A Fresh Website", u: "https://a-fresh.website", d: "Recent creative websites, curated.", t: ["Web", "Inspiration"] },
    { n: "Crypto Design Club", u: "https://cryptodesign.club", d: "An archive of Web3 and crypto product design.", t: ["Web", "App", "Inspiration"] },
    { n: "Utopia Tokyo", u: "https://www.utopiatokyo.com", d: "Japanese-flavoured interactive web design.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "Laxspace", u: "https://www.laxspace.co", d: "A minimal design studio reference.", t: ["Web", "Portfolio", "Inspiration"] },
    { n: "Sons and Daughters", u: "https://sonsanddaughters.xyz", d: "A cinematic creative-agency site.", t: ["Web", "Motion", "Inspiration"] },
    { n: "Sutera", u: "https://www.sutera.ch", d: "A Swiss-style brand website.", t: ["Web", "Branding", "Inspiration"] },
    { n: "Vert Menthe × Dault-Lafon", u: "https://thevertmenthe.dault-lafon.fr", d: "A luxury brand interactive web experience.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "Drum Spirit", u: "https://www.drumspirit.be", d: "A motion-driven interactive site.", t: ["Web", "Motion", "Inspiration"] },
    { n: "Getty Tracing Art", u: "https://www.getty.edu/tracingart", d: "An interactive digital exhibition.", t: ["Web", "Interaction", "Inspiration"] },
    { n: "igloo", u: "https://www.igloo.inc", d: "A creative agency website.", t: ["Web", "Portfolio", "Inspiration"] },
    { n: "Handheld Design", u: "https://handheld.design", d: "Mobile app UI design references.", t: ["App", "Inspiration"] },
    { n: "Page Flows", u: "https://pageflows.com", d: "Recordings of real app user flows.", t: ["App", "UX", "Inspiration"] },
    { n: "iOS Icon Gallery", u: "https://www.iosicongallery.com", d: "A collection of iOS app icons.", t: ["Icon", "App", "Inspiration"] },
    { n: "Pushkeen.AI", u: "https://pushkeen.ai", d: "Real push-notification patterns from apps.", t: ["App", "UX", "Inspiration"] },
    { n: "Scrnshts", u: "https://scrnshts.club", d: "An archive of App Store screenshot design.", t: ["App", "Graphic Design", "Inspiration"] },
    { n: "Auto Interfaces", u: "https://www.autointerfaces.com", d: "Car infotainment UI references.", t: ["App", "UX", "Inspiration"] },
    { n: "HUDS + GUIS", u: "https://www.hudsandguis.com", d: "Game and sci-fi HUD / GUI design.", t: ["Graphic Design", "App", "Inspiration"] },
    { n: "SaaSFrame", u: "https://www.saasframe.io", d: "SaaS UI and dashboard examples.", t: ["Web", "App", "Inspiration"] },
    { n: "SaaS Interface", u: "https://saasinterface.com", d: "SaaS web app UI references.", t: ["Web", "App", "Inspiration"] },
    { n: "Mindsparkle Mag", u: "https://mindsparklemag.com", d: "A magazine of web, branding, graphic and motion.", t: ["Web", "Branding", "Inspiration"] },
    { n: "Nicelydone", u: "https://nicelydone.club", d: "Curated SaaS and web app UI.", t: ["Web", "App", "Inspiration"] },
    { n: "Webframe", u: "https://webframe.xyz", d: "A screenshot archive of web app UI.", t: ["Web", "App", "Inspiration"] },
    { n: "Really Good Emails", u: "https://www.reallygoodemails.com", d: "Email and newsletter design examples.", t: ["Email", "Inspiration"] },
    { n: "Vidclue", u: "https://vidclue.com", d: "Short-form and advertising video references.", t: ["Motion", "Inspiration"] },
    { n: "Dieline", u: "https://thedieline.com", d: "A dedicated package design archive.", t: ["Branding", "Graphic Design", "Inspiration"] },
    { n: "Interface Index", u: "https://interface-index.com", d: "A broad collection of interface design.", t: ["App", "Web", "Inspiration"] },
    { n: "ChainGPT Labs", u: "https://labs.chaingpt.org", d: "AI and Web3 product UI examples.", t: ["App", "AI Design", "Inspiration"] },
    { n: "Commerce Cream", u: "https://commercecream.com", d: "Curated ecommerce website design.", t: ["Ecommerce", "Web", "Inspiration"] },
    { n: "ecomm.design", u: "https://ecomm.design", d: "Global ecommerce UI examples.", t: ["Ecommerce", "Web", "Inspiration"] },
    { n: "tiny blocks", u: "https://www.tinyblocks.cc", d: "A collection of ecommerce UI components.", t: ["Ecommerce", "Component", "Inspiration"] },
    { n: "PFolios", u: "https://pfolios.net", d: "Curated designer portfolios.", t: ["Portfolio", "Inspiration"] },
    { n: "Bestfolios", u: "https://www.bestfolios.com", d: "An archive of standout designer portfolios.", t: ["Portfolio", "Inspiration"] },
    { n: "Prettyfolio", u: "https://www.prettyfolio.com", d: "Portfolio and case-study references.", t: ["Portfolio", "Inspiration"] },
    { n: "Pafolios", u: "https://pafolios.com", d: "Curated creative portfolios.", t: ["Portfolio", "Inspiration"] },
    { n: "Jessica Wells", u: "https://www.jessicawells.co", d: "A strong individual portfolio example.", t: ["Portfolio", "Inspiration"] },
    { n: "Lummi", u: "https://www.lummi.ai", d: "Free AI-generated stock imagery.", t: ["Image", "AI Design", "Library"] },
    { n: "500px", u: "https://500px.com", d: "A high-quality photography portfolio platform.", t: ["Image", "Portfolio"] },
    { n: "Flickr", u: "https://www.flickr.com", d: "A long-running global photo community.", t: ["Image", "Library"] },
    { n: "YouPic", u: "https://youpic.com", d: "Photographer work and inspiration.", t: ["Image", "Inspiration"] },
    { n: "ViewBug", u: "https://www.viewbug.com", d: "An award-focused photo gallery.", t: ["Image", "Inspiration"] },
    { n: "Eyecandy", u: "https://eyecannndy.com", d: "A visual dictionary of motion techniques.", t: ["Motion", "Interaction", "Inspiration"] },
    { n: "Brands in Motion", u: "https://www.brandsinmotion.xyz", d: "Brand motion design references.", t: ["Motion", "Branding", "Inspiration"] },
    { n: "Art of the Title", u: "https://www.artofthetitle.com", d: "An archive of film and TV title sequences.", t: ["Motion", "Inspiration"] },
    { n: "Wannathis Mockups", u: "https://wannathis.one/mockups", d: "High-quality device and branding mockups.", t: ["Mockup", "Library"] },
    { n: "Smartphone Mockups", u: "https://smartphonemockup.com", d: "A PSD mockup library focused on phones.", t: ["Mockup", "Library"] },
    { n: "Craftwork", u: "https://craftwork.design", d: "UI kits, mockups, illustrations and icons.", t: ["Mockup", "Icon", "Library"] },
    { n: "Shots", u: "https://shots.so", d: "Quickly generate browser and device mockups.", t: ["Mockup", "Tool"] },
    { n: "Mockups Design", u: "https://mockups-design.com", d: "A free PSD mockup library.", t: ["Mockup", "Library"] },
    { n: "Unblast Mockups", u: "https://unblast.com/mockups", d: "Assorted free mockup resources.", t: ["Mockup", "Library"] },
    { n: "Spline Mockups", u: "https://spline.design/community", d: "3D-based device and product mockups.", t: ["Mockup", "3D", "Library"] },
    { n: "Mockup World", u: "https://www.mockupworld.co", d: "Free mockups, curated by category.", t: ["Mockup", "Library"] },
    { n: "Bendito Mockup", u: "https://benditomockup.com", d: "Apple device and brand mockups.", t: ["Mockup", "Library"] },
    { n: "Creatoom", u: "https://creatoom.com/mockups", d: "A PSD-based free mockup library.", t: ["Mockup", "Library"] },
    { n: "Package Mockups", u: "https://packagemockups.com", d: "Mockups for packaging, boxes and labels.", t: ["Mockup", "Branding", "Library"] },
    { n: "Freebiesbug", u: "https://freebiesbug.com", d: "Free UI kits, mockups and icon resources.", t: ["Mockup", "Icon", "Library"] },
    { n: "Mr.Mockup", u: "https://mrmockup.com", d: "Premium brand and device mockups.", t: ["Mockup", "Library"] },
    { n: "Mockup Maison", u: "https://mockup.maison", d: "A 200+ piece premium mockup collection.", t: ["Mockup", "Library"] },
    { n: "LS Graphics", u: "https://www.ls.graphics/free-mockups", d: "High-quality Figma, PSD and Sketch mockups.", t: ["Mockup", "Library"] },
    { n: "Made Marked Goods", u: "https://mademarkedgoods.gumroad.com", d: "Apple device and premium mockup assets.", t: ["Mockup", "Library"] },
    { n: "Emboss card", u: "https://emboss-card.com/", d: "Open-source card-style embossing effect.", t: ["Component", "Graphic Design"] },
    { n: "Clarity", u: "https://clarity.microsoft.com/lang/ko-kr", d: "Free web analytics with heatmaps and session replay.", t: ["Tool", "UX"] },
    { n: "GSAP", u: "https://gsap.com", d: "High-performance JavaScript animation library.", t: ["Tool", "Motion", "Interaction"] },
    { n: "Norrly", u: "https://norrly.io", d: "A Nordic-minimal brand design studio.", t: ["Web", "Branding", "Inspiration"] },
    { n: "Getlayes", u: "https://getlayes.ai", d: "AI-generated frontend layouts and design.", t: ["AI Design", "Tool"] },
    { n: "Aceternity", u: "https://ui.aceternity.com", d: "Animated React and Tailwind UI components.", t: ["Component", "Motion", "Library"] },
    { n: "Internet Archive", u: "https://archive.org", d: "The world's largest library of web and media.", t: ["Library"] },
    { n: "The East Asian Graphics Archive", u: "https://eastasiangraphicsarchive.com", d: "An archive of East Asian graphic design.", t: ["Graphic Design", "Inspiration"] },
    { n: "Motionsites", u: "https://motionsites.ai", d: "Recent motion-heavy websites, collected.", t: ["Motion", "Web", "Inspiration"] },
    { n: "Nosignups", u: "https://nosignups.net/", d: "Web services you can use without an account.", t: ["Tool", "Library"] },
    { n: "Freesourc", u: "https://freesourc.es/", d: "A broad curation of free design and dev resources.", t: ["Library"] },
    { n: "Doodle Font", u: "https://fontesk.com/your-doodle-font/", d: "Turn your handwriting into a font.", t: ["Font", "Tool"] },
    { n: "Type Tools", u: "https://typetools.co/", d: "Utilities for typography and fonts.", t: ["Font", "Tool"] },
    { n: "Uncut", u: "https://uncut.wtf/", d: "An archive of open-source and free foundry fonts.", t: ["Font", "Library"] },
    { n: "Free Faces Gallery", u: "https://www.freefaces.gallery/", d: "Curated high-quality free typefaces.", t: ["Font", "Library"] },
    { n: "TypeType", u: "https://typetype.org/", d: "A global independent type foundry.", t: ["Font", "Library"] },
    { n: "Fontshare", u: "https://www.fontshare.com/", d: "Free web fonts from the Indian Type Foundry.", t: ["Font", "Library"] },
    { n: "Metaflop", u: "https://www.metaflop.com/", d: "A parametric font modulator.", t: ["Font", "Tool"] },
    { n: "Giulia Boge", u: "https://giuliaboge.com/", d: "Typefaces by type designer Giulia Boge.", t: ["Font", "Portfolio"] },
    { n: "Display", u: "https://displaytypefaces.com/", d: "A foundry of display typefaces.", t: ["Font", "Library"] },
    { n: "Bretagne", u: "https://www.collletttivo.it/", d: "The open-source display typeface Bretagne.", t: ["Font", "Library"] },
    { n: "Nouvelle Noire", u: "https://nouvellenoire.ch/", d: "A Swiss independent type foundry.", t: ["Font", "Library"] },
    { n: "Hal Typefaces", u: "https://haltypefaces.com/", d: "An independent type design foundry.", t: ["Font", "Library"] },
    { n: "Pangram Pangram", u: "https://pangrampangram.com/", d: "A foundry of premium and free typefaces.", t: ["Font", "Library"] },
    { n: "BKLit UI", u: "https://bklitui.com/", d: "Open-source charts and UI on shadcn/ui.", t: ["Component", "Library"] },
    { n: "PageSpeed Insights", u: "https://pagespeed.web.dev/", d: "Google's web loading speed and performance test.", t: ["Tool", "UX"] },
    { n: "WebAIM Contrast Checker", u: "https://webaim.org/resources/contrastchecker/", d: "Check colour contrast for accessibility.", t: ["Tool", "Color", "UX"] },
    { n: "Backdrop.love", u: "https://backdrop.love/", d: "Background gradients and visual patterns.", t: ["Color", "Image", "Library"] },
    { n: "21st.dev", u: "https://21st.dev/", d: "A community for React and Tailwind UI components.", t: ["Component", "Library"] },
    { n: "Animmasterlib.dev", u: "https://animmasterlib.dev/", d: "A library for interactive web and motion.", t: ["Motion", "Interaction", "Library"] },
    { n: "Raylight", u: "https://www.raylight.app/", d: "Generate 3D motion and showcase video.", t: ["3D", "Motion", "Tool"] },
    { n: "Vibe UI", u: "https://vibeui.online/", d: "A library of UI prompts for AI coding.", t: ["AI Design", "Component", "Library"] },
    { n: "60fps.design", u: "https://60fps.design/", d: "High-quality app and web motion references.", t: ["Motion", "Interaction", "Inspiration"] },
    { n: "Booklet", u: "https://www.booklet-app.com/", d: "A web-based reading library and its design.", t: ["Library", "Web"] },
    { n: "Another Graphic", u: "https://anothergraphic.org/", d: "A typography-led graphic design archive.", t: ["Graphic Design", "Font", "Inspiration"] },
    { n: "Scanned Fashion World", u: "https://www.scannedfashionworld.com/", d: "High-res scans of fashion magazines and lookbooks.", t: ["Graphic Design", "Image", "Inspiration"] },
    { n: "Watermelon UI", u: "https://ui.watermelon.sh/", d: "Interactive animated React components.", t: ["Component", "Motion", "Library"] },
    { n: "Cult UI", u: "https://www.cult-ui.com/", d: "React and Tailwind components for design engineers.", t: ["Component", "Library"] },
    { n: "Skiper UI", u: "https://skiper-ui.com/", d: "Motion UI components on Next.js and shadcn/ui.", t: ["Component", "Motion", "Library"] },
    { n: "Shapefest", u: "https://www.shapefest.com/", d: "High-resolution free 3D shapes and graphics.", t: ["3D", "Image", "Library"] },
    { n: "Vengeance UI", u: "https://www.vengenceui.com/", d: "Hover and scroll animation React components.", t: ["Component", "Motion", "Library"] },
    { n: "ThreeUI", u: "https://threeui.com/", d: "3D web components on Three.js and WebGL.", t: ["3D", "Component", "Library"] },
  ];
})(typeof window !== "undefined" ? window : this);
